export default [
  {
    name: "Amazon Deliveries",
    id: "e1",
    data: (2018, 11, 24, 10, 33, 30, 0),
    rating: 4,
    description: "This was a delivery of the laptop",
    isMailBoxAccessed: true,
    voiceMessages: [],
    imageURL: "./dummyImages/e1",
  },
  {
    name: "James Visiting",
    id: "e2",
    data: (2019, 10, 5, 9, 23, 30, 0),
    rating: 2,
    description: "This was the event when james visited",
    isMailBoxAccessed: false,
    voiceMessages: [],
    imageURL: "./dummyImages/e2",
  },
  {
    name: "Pizza Hut delivery",
    id: "e3",
    data: (2019, 11, 12, 16, 15, 30, 0),
    rating: 5,
    description: "This was a pizza delivery from the pizza hut",
    isMailBoxAccessed: true,
    voiceMessages: [],
    imageURL: "./dummyImages/e3",
  },
  {
    name: "Ebay delivery",
    id: "e4",
    data: (2020, 11, 12, 16, 15, 30, 0),
    rating: 1,
    description: "Tv delivery from the EBAY",
    isMailBoxAccessed: true,
    voiceMessages: [],
    imageURL: "./dummyImages/e3",
  },
];
