export const PreviousEventsList = [
  {
    name: "Amazon Deliveries",
    id: "e1",
    date: new Date(2018, 11, 24, 10, 33, 30, 0),
    rating: 4,
    description: "This was a delivery of the laptop",
    isMailBoxAccessed: true,
    voiceMessages: [],
    imageURL: "../dummy data/dummyImages/e1.jpg",
  },
  {
    name: "James Visiting",
    id: "e2",
    date: new Date(2019, 10, 5, 9, 23, 30, 0),
    rating: 2,
    description: "This was the event when james visited",
    isMailBoxAccessed: false,
    voiceMessages: [],
    imageURL: "../dummy data/dummyImages/e2.jpg",
  },
  {
    name: "Pizza Hut delivery",
    id: "e3",
    date: new Date(2019, 11, 12, 16, 15, 30, 0),
    rating: 5,
    description: "This was a pizza delivery from the pizza hut",
    isMailBoxAccessed: true,
    voiceMessages: [],
    imageURL: "../dummy data/dummyImages/e3.jpg",
  },
  {
    name: "Ebay delivery",
    id: "e4",
    date: new Date(2020, 11, 12, 16, 15, 30, 0),
    rating: 1,
    description: "Tv delivery from the EBAY",
    isMailBoxAccessed: true,
    voiceMessages: [],
    imageURL: "../dummy data/dummyImages/e3.jpg",
  },
];
